version: "3"

services:
  ### external modules
  postgres:
    image: postgres:11.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"


  concept-catalog:
    image: dcatno/concept-catalog:latest
    expose:
      - "8080"
    depends_on:
      - postgres

  concept-catalog-gui:
    image: dcatno/concept-catalog-gui:latest
    expose:
      - "8080"