version: "3"

services:
  ### external modules

  postgres:
    restart: always
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"


  ### java modules

  concept-catalogue:
    ports:
      - "8200:8080"
    environment:
      - JAVA_OPTS=-Djava.security.egd=file:/dev/./urandom -Xmx256M -Dspring.profiles.active=docker
      - FDK_SQL_JDBC_CONNECTION=jdbc:postgresql://postgres:5432/postgres?currentSchema=conceptRegistration
      - FDK_SQL_USERNAME=postgres
      - FDK_SQL_PASSWORD=password
      - SSO_HOST


  ### nodejs modules

  concept-catalogue-gui:
    #interestingly, if multiple docker-compose files are combined, then "." gets wrong value
    build: ../concept-catalogue-gui
    ports:
      - "8202:3111"
    volumes:
      - ../concept-catalogue-gui/src:/usr/src/app/src
    environment:
      - CONCEPT_REGISTRATION_API=http://localhost:8200
      - REGISTRATION_HOST=https://localhost:8098
      - PUBLISHER_API=https://www.ut1.fellesdatakatalog.brreg.no
      - PUBLISHER_DATA_AUTHORIZATION=Basic ZmRrOkJSUkVH
      - SSO_HOST=http://localhost:8084