version: "3"

services:
  ### external modules
  postgres:
    image: postgres:11.2
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"


  concept-catalogue:
    image: dcatno/concept-catalogue:latest
    expose:
      - "8080"
    depends_on:
      - postgres

  concept-catalogue-gui:
    image: dcatno/concept-catalogue-gui:latest