export const SEARCH_CONCEPTS_REQUESTED = 'SEARCH_CONCEPTS_REQUESTED' as const;
export const SEARCH_CONCEPTS_SUCCEEDED = 'SEARCH_CONCEPTS_SUCCEEDED' as const;
export const SEARCH_CONCEPTS_FAILED = 'SEARCH_CONCEPTS_FAILED' as const;
