openapi: 3.0.2
info:
  description: Tilgjengeliggjør begreper fra Begrepskatalog
  version: '1.0'
  title: Begrepskatalog API
  contact:
    name: Brønnøysundregistrene
    url: 'https://fellesdatakatalog.brreg.no'
    email: fellesdatakatalog@brreg.no
  license:
    name: License of API
    url: 'http://data.norge.no/nlod/no/2.0'
tags:
  - name: begrepskatalog
    description: Begrepskatalog API
servers:
  - url: 'https://begrepskatalog.fellesdatakatalog.brreg.no/api'
    description: Produksjonsversjon av API server
paths:
  /begreper:
    post:
      tags:
        - begrepskatalog
      description: opprette nytt begrep
      operationId: createBegrep
      responses:
        '201':
          description: Created
          headers:
            Location:
              schema:
                type: string
              description: url til det nye begrepet
        '409':
          description: Ulovlig verdier i begrep
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feilmelding"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Begrep'
    get:
      tags:
        - begrepskatalog
      description: Returnerer en samling begreper for en gitt virksomhet
      operationId: getBegrep
      parameters:
        - name: orgNummer
          in: query
          description: Virksomhetens organisasjonsnummer
          required: true
          schema:
            type: string
        - name: status
          in: query
          description: begrepets status
          required: false
          schema:
            $ref: "#/components/schemas/Status"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Begrep'
  /begreper/{id}:
    get:
      tags:
        - begrepskatalog
      description: Hent et spesifikt begrep
      operationId: getBegrepById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Begrep"
    put:
      tags:
        - begrepskatalog
      description: Oppdatere detaljer på et begrep
      operationId: setBegrepById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
        - name: validate
          in: query
          description: Om begrepet skal valideres
          required: false
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Begrep"
        '409':
          description: Ulovlig verdier i begrep
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feilmelding"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Begrep'
    delete:
      tags:
        - begrepskatalog
      description: slette et begrep
      operationId: deleteBegrepById
      parameters:
        - name: id
          in: path
          description: id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
components:
  schemas:
    Begrep:
        type: object
        description: Et begrep
        properties:
          id:
            type: string
            description: system-generert id (GUID)
          status:
            $ref: "#/components/schemas/Status"
          anbefaltTerm:
            type: string
          definisjon:
            type: string
          kilde:
            type: string
          merknad:
            type: string
          ansvarligVirksomhet:
            $ref: "#/components/schemas/Virksomhet"
          eksempel:
            type: string
          fagområde:
            type: string
          bruksområde:
            type: string
          verdiområde:
            type: string
            description: omfang
          kontaktpunkt:
            type: string
          gyldigFom:
            type: string
            format: date
          forholdTilKilde:
            type: string
    Virksomhet:
      type: object
      description: Ansvarlig virksomhet for begrepet [dct:publisher]
      properties:
        uri:
          type: string
          description: Lenke til the virksomhet i Brønnøysundregistrene
        id:
          type: string
          description: organisasjonsnummer
        navn:
          type: string
          description: Navnet til virksomheten slik den er oppgitt i Brønnøysundregistrene
        orgPath:
          type: string
        prefLabel:
          type: string
    Status:
      type: string
      enum:
      - utkast
      - godkjent
      - publisert
    Feilmelding:
      type: object
      required:
      - melding
      properties:
        melding:
          type: string
