name: Build dev

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  build-dev-image:
    name: Build and test dev image on PR from dependabot
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/dev/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        id: docker_build
        if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./dev.Dockerfile
          push: false
          cache-from: type=local,src=/tmp/dev/.buildx-cache
          cache-to: type=local,dest=/tmp/dev/.buildx-cache
          build-args:  |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}